# Generated by Django 3.2.7 on 2021-09-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
