# Generated by Django 3.2.7 on 2021-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('public', 'Public'), ('draft', 'draft')], default='public', max_length=6),
        ),
    ]
